### ISSUE TITLE
Just tried with both orace java (yuck!) and amazon Correto - doesn't work with wav files

### ISSUE THREAD

**Issue by muonIT** [nwaldispuehl/interval-music-compositor#59]
Hi,
I just tried to run the program under Win10 (19.09) with first 64 bit JRE from Amazon (Correto) and then, since it didn't produce any output (or error messages), with Oracle JRE.
In both cases nothing happened. The music files are 8kHz, stereo WAV files. I mean to create answering messages for a telephony system that way.
Music files are here: https://oc.muon.de/index.php/s/by2qYSSQZBPXwia

**Comment by nwaldispuehl** [comment]
Hi, thank you reaching out.
I did a first test -- although on Linux with Oracle JDK 1.8 -- and your sound files are processed properly ('Help' -> 'Debug Log'):
```
[...] - Added new file: .../audiohub_2015-00594-622_keep-em-dry.wav
[...] - Selected WaveAudioFileDecoder for decoding .../audiohub_2015-00594-622_keep-em-dry.wav
[...] - Original format: PCM_SIGNED 8000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian
[...] - Converted format: PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian
[...] - audiohub_2015-00594-622_keep-em-dry.wav volume ratio: 1.0425057
[...] - audiohub_2015-00594-622_keep-em-dry.wav duration: 136594 ms
[...] - audiohub_2015-00594-622_keep-em-dry.wav BPM: 120
[...] - Setting status to OK for audiohub_2015-00594-622_keep-em-dry.wav
```
I am currently downloading a Microsoft Windows 10 VM to test with this Amazon Corretto JRE.

It should actually run with a Amazon Corretto (OpenJDK). Currently, only version 1.8 is supported, though. With version 11 the software will not start.

Can you give me additional information about what steps lead to your result 'nothing happened'? The software starts, you drag the tracks into it, and after having chosen some music duration and intervals, you press the 'Process' button and nothing happens? Or does it not start at all? If the latter, you probably used the newer JRE.

**Comment by muonIT** [comment]
Yeah - it was a layer 8 problem.. I didn't add duration and intervals - and hence nothing was happening when I pressed "Process".
So sorry for wasting your time!
Some good stuff came out of it anyway: since Oracle is pressuring commercial users an alternative might be the amazon corretto JRE - in my test it worked with your software! :-)
And maybe you can add a dummy user function and popup an alert if no duration/interval is chosen.

Sorry again and thanks for your efforts!
Best regards!
Udo

**Comment by nwaldispuehl** [comment]
No worries about the time, and thanks for coming back.

The next version (compatible with Java 11+) will ship with a bundled JRE which most likely will be an OpenJRE anyway, so no (dedicated) installation of Java will be needed anymore.
