### ISSUE TITLE
Advanced Feature of mixing different break times does not work

### ISSUE THREAD

**Issue by berndludwig** [nwaldispuehl/interval-music-compositor#60]
I have tried to create a new file with 30 sec. music snipets and 15 sec. breaks - 6 iterations of action and then a 120 sec break:
Advanced Sound Pattern: 30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Advanced Break Pattern: 15,15,15,15,15,120,15,15,15,15,15,120,15,15,15,15,15
It then creates only 15 sec breaks at any occasion.
See debug file and output .txt file[
[30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_120b_30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_120b_30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_15b-x1.playlist.txt](https://github.com/nwaldispuehl/interval-music-compositor/files/4570511/30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_120b_30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_120b_30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_15b-x1.playlist.txt)
[Debug.txt.txt](https://github.com/nwaldispuehl/interval-music-compositor/files/4570514/Debug.txt.txt)

](url)

**Comment by nwaldispuehl** [comment]
Thanks for the bug report. Will look into it.

**Comment by nwaldispuehl** [comment]
My first thought: According to the track list your break track has a length of 120s:

      00:30, [Duration: 00:15], 06 Silence - 120 Seconds.mp3 (-1 bpm[!]), Extract: 00:05-00:20

Every music track is stripped of its first and last 5 seconds thus the useable length is always `length - 10s`. Quite possible that the software is here and acts unpredictable.

Does it work if you remove the break track?

**Comment by nwaldispuehl** [comment]
The software does not verify for track length in the advanced pattern mode and is upset if something does not add up: 
- it crashes if there is a too short track in the music tracks, and
- swallows the break if there is a too short break track present.

I will fix the issue in the next weeks.

Workaround: Manually verify for sufficient track length; mind the additional 5 seconds each at the beginning and end which have to be accounted for. In your case use at least a 130 second silence track (if possible). 
Alternatively -- if this is indeed silence in your 'Silence' break track -- just omit it; the software adds silence in the breaks as well.

**Comment by berndludwig** [comment]
I didn´t realize that if I omit the break music peace silence is automatically added.
I have re-run the processing with the advanced mode and it works as planned.

Thanks for the clarification and help. See attached screen shot.
![Update - Interval Music Composer - 20200507](https://user-images.githubusercontent.com/25746665/81273697-9089fd80-904f-11ea-8c66-acad8e5fb0b5.jpg)
[30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_120b-x3.playlist.txt](https://github.com/nwaldispuehl/interval-music-compositor/files/4591819/30s_15b_30s_15b_30s_15b_30s_15b_30s_15b_30s_120b-x3.playlist.txt)

This fixes my issue - Thanks
