### ISSUE TITLE
Test "Utf8BundleIntegrationTest.shouldHandleEncodedUmlauts" fails

### ISSUE THREAD

**Issue by xehpuk** [nwaldispuehl/interval-music-compositor#61]
```
Expected: is "Ã¤Ã¶Ã¼Ã¡Ã³Ãº"
     but: was "äöüáóú"
```

What I did: Cloned this repo and ran `gradlew check`.

**Comment by nwaldispuehl** [comment]
Hi, thanks for the message.

If I clone the repo and execute `./gradlew check` I get a green build. 
Both the class `Utf8BundleIntegrationTest.java` and the properties file `test.properties` are in UTF-8 encoding. 
Do you perform some character set conversion on clone by any chance?

**Comment by xehpuk** [comment]
> Do you perform some character set conversion on clone by any chance?

Not that I know of. IntelliJ IDEA displays both source files fine in UTF-8. But when I open the compiled class file, it looks like this:

```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package ch.retorte.intervalmusiccompositor.commons;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;
import org.junit.Test;

public class Utf8BundleIntegrationTest {
    public Utf8BundleIntegrationTest() {
    }

    @Test
    public void shouldHandleEncodedUmlauts() {
        String umlautsAndAccents = "Ã¤Ã¶Ã¼Ã¡Ã³Ãº";
        MessageFormatBundle testBundle = Utf8Bundle.getBundle("test");
        String retrievedString = testBundle.getString("myUmlautsAndAccents", new Object[0]);
        Assert.assertThat(retrievedString, CoreMatchers.is(umlautsAndAccents));
    }
}
```

**Comment by xehpuk** [comment]
Adding

```gradle
compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
```

or

```gradle
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
```

to `/build.gradle` after

```gradle
apply plugin:'java'
```

fixed it for me.

I'm on Windows, which seems to be relevant.

**Comment by nwaldispuehl** [comment]
Ah, nice find, thanks!
If you like you can do a PR with it. 
Otherwise I will add the options with one of the next iterations myself.
